### ISSUE TITLE
Branding the site for seAp

### ISSUE THREAD

**Issue by rosejbon** [neontribe/ca-seap#6]
## Description

We will need to brand the site so it is inline with the new seAp branding

## Plan

- [x] @HedgehogHolly to meet with Paul about seAp's new brand design
- [x] @HedgehogHolly to mock up designs for Liz
- [x] Get design sign off
- [x] Implement changes

## Acceptance criteria
- [x] design is implemented as closed as possible to the signed off version - [available here](https://drive.google.com/file/d/0ByiaMChTtEUWYkMwYnZqWllsVVBybVpyNEZRQ0d5RExaLXV3/view?usp=sharing)
- [x] issue #13 is tested successfully
- [x] issue #24 is tested successfully
- [x] issue #29 is tested successfully

**Comment by rosejbon** [comment]
Branding is available from the 26th Sept

**Comment by rosejbon** [comment]
Update from Liz - we can use all new branding on the site, including the new logo

**Comment by rosejbon** [comment]
Closing as Liz has signed off on the designs: https://drive.google.com/file/d/0ByiaMChTtEUWYkMwYnZqWllsVVBybVpyNEZRQ0d5RExaLXV3/view?usp=sharing

**Comment by jermyk** [comment]
@katjam 
AC required for this card.

**Comment by AlinChindea** [comment]
> @katjam
> AC required for this card.

@jermyk on it but it will be just references to other issues where the design was implemented

**Comment by jermyk** [comment]
## Acceptance criteria
- [x] design is implemented as closed as possible to the signed off version - [available here](https://drive.google.com/file/d/0ByiaMChTtEUWYkMwYnZqWllsVVBybVpyNEZRQ0d5RExaLXV3/view?usp=sharing)
- [x] issue #13 is tested successfully
- [x] issue #24 is tested successfully
- [x] issue #29 is tested successfully
